//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 03:58:57 AM CEST 
//


package com.timrobot.vaccapp.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.timrobot.vaccapp.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZahtevRazlogZaOdbijanje_QNAME = new QName("http://tim.robot/zahtev_za_sertifikat", "Razlog_za_odbijanje");
    private final static QName _ObrazacPodaciOPacijentuSedisteSocijalneZastite_QNAME = new QName("http://tim.robot/obrazac_saglasnosti_za_imunizaciju", "Sediste_socijalne_zastite");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.timrobot.vaccapp.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObrazacInteresovanja }
     * 
     */
    public ObrazacInteresovanja createObrazacInteresovanja() {
        return new ObrazacInteresovanja();
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link Potvrda }
     * 
     */
    public Potvrda createPotvrda() {
        return new Potvrda();
    }

    /**
     * Create an instance of {@link Obrazac }
     * 
     */
    public Obrazac createObrazac() {
        return new Obrazac();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link Sertifikat }
     * 
     */
    public Sertifikat createSertifikat() {
        return new Sertifikat();
    }

    /**
     * Create an instance of {@link Obrazac.EvidencijaOVakcinaciji }
     * 
     */
    public Obrazac.EvidencijaOVakcinaciji createObrazacEvidencijaOVakcinaciji() {
        return new Obrazac.EvidencijaOVakcinaciji();
    }

    /**
     * Create an instance of {@link Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama }
     * 
     */
    public Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama createObrazacEvidencijaOVakcinacijiPodaciOIzvrsenimImunizacijama() {
        return new Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama();
    }

    /**
     * Create an instance of {@link Obrazac.PodaciOPacijentu }
     * 
     */
    public Obrazac.PodaciOPacijentu createObrazacPodaciOPacijentu() {
        return new Obrazac.PodaciOPacijentu();
    }

    /**
     * Create an instance of {@link Obrazac.PodaciOPacijentu.Drzavljanstvo }
     * 
     */
    public Obrazac.PodaciOPacijentu.Drzavljanstvo createObrazacPodaciOPacijentuDrzavljanstvo() {
        return new Obrazac.PodaciOPacijentu.Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Izvestaj.PeriodIzvestaja }
     * 
     */
    public Izvestaj.PeriodIzvestaja createIzvestajPeriodIzvestaja() {
        return new Izvestaj.PeriodIzvestaja();
    }

    /**
     * Create an instance of {@link BrojVakcina }
     * 
     */
    public BrojVakcina createBrojVakcina() {
        return new BrojVakcina();
    }

    /**
     * Create an instance of {@link ObrazacInteresovanja.LicniPodaci }
     * 
     */
    public ObrazacInteresovanja.LicniPodaci createObrazacInteresovanjaLicniPodaci() {
        return new ObrazacInteresovanja.LicniPodaci();
    }

    /**
     * Create an instance of {@link Izvestaj.PodaciODatimDozama }
     * 
     */
    public Izvestaj.PodaciODatimDozama createIzvestajPodaciODatimDozama() {
        return new Izvestaj.PodaciODatimDozama();
    }

    /**
     * Create an instance of {@link Izvestaj.RaspodelaPoProizvodjacima }
     * 
     */
    public Izvestaj.RaspodelaPoProizvodjacima createIzvestajRaspodelaPoProizvodjacima() {
        return new Izvestaj.RaspodelaPoProizvodjacima();
    }

    /**
     * Create an instance of {@link Izvestaj.Datum }
     * 
     */
    public Izvestaj.Datum createIzvestajDatum() {
        return new Izvestaj.Datum();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link Potvrda.PodaciPacijenta }
     * 
     */
    public Potvrda.PodaciPacijenta createPotvrdaPodaciPacijenta() {
        return new Potvrda.PodaciPacijenta();
    }

    /**
     * Create an instance of {@link TDozaVakcine }
     * 
     */
    public TDozaVakcine createTDozaVakcine() {
        return new TDozaVakcine();
    }

    /**
     * Create an instance of {@link TZdravstvenaUstanova }
     * 
     */
    public TZdravstvenaUstanova createTZdravstvenaUstanova() {
        return new TZdravstvenaUstanova();
    }

    /**
     * Create an instance of {@link TDatum }
     * 
     */
    public TDatum createTDatum() {
        return new TDatum();
    }

    /**
     * Create an instance of {@link Obrazac.PodaciOSaglasnosti }
     * 
     */
    public Obrazac.PodaciOSaglasnosti createObrazacPodaciOSaglasnosti() {
        return new Obrazac.PodaciOSaglasnosti();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPrimljenaVakcina }
     * 
     */
    public TPrimljenaVakcina createTPrimljenaVakcina() {
        return new TPrimljenaVakcina();
    }

    /**
     * Create an instance of {@link TIme }
     * 
     */
    public TIme createTIme() {
        return new TIme();
    }

    /**
     * Create an instance of {@link TPrezime }
     * 
     */
    public TPrezime createTPrezime() {
        return new TPrezime();
    }

    /**
     * Create an instance of {@link TNazivVakcine }
     * 
     */
    public TNazivVakcine createTNazivVakcine() {
        return new TNazivVakcine();
    }

    /**
     * Create an instance of {@link TDatumIzdavanja }
     * 
     */
    public TDatumIzdavanja createTDatumIzdavanja() {
        return new TDatumIzdavanja();
    }

    /**
     * Create an instance of {@link Termin }
     * 
     */
    public Termin createTermin() {
        return new Termin();
    }

    /**
     * Create an instance of {@link Zahtev.PodaciOPodnosiocu }
     * 
     */
    public Zahtev.PodaciOPodnosiocu createZahtevPodaciOPodnosiocu() {
        return new Zahtev.PodaciOPodnosiocu();
    }

    /**
     * Create an instance of {@link Sertifikat.PodaciOSertifikatu }
     * 
     */
    public Sertifikat.PodaciOSertifikatu createSertifikatPodaciOSertifikatu() {
        return new Sertifikat.PodaciOSertifikatu();
    }

    /**
     * Create an instance of {@link Sertifikat.PodaciOPacijentu }
     * 
     */
    public Sertifikat.PodaciOPacijentu createSertifikatPodaciOPacijentu() {
        return new Sertifikat.PodaciOPacijentu();
    }

    /**
     * Create an instance of {@link TDozaVakcinacije }
     * 
     */
    public TDozaVakcinacije createTDozaVakcinacije() {
        return new TDozaVakcinacije();
    }

    /**
     * Create an instance of {@link TKovidTest }
     * 
     */
    public TKovidTest createTKovidTest() {
        return new TKovidTest();
    }

    /**
     * Create an instance of {@link Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru }
     * 
     */
    public Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru createObrazacEvidencijaOVakcinacijiPodaciOLekaru() {
        return new Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru();
    }

    /**
     * Create an instance of {@link Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije }
     * 
     */
    public Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije createObrazacEvidencijaOVakcinacijiPodaciOIzvrsenimImunizacijamaPrivremeneKontraindikacije() {
        return new Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link Obrazac.PodaciOPacijentu.SedisteSocijalneZastite }
     * 
     */
    public Obrazac.PodaciOPacijentu.SedisteSocijalneZastite createObrazacPodaciOPacijentuSedisteSocijalneZastite() {
        return new Obrazac.PodaciOPacijentu.SedisteSocijalneZastite();
    }

    /**
     * Create an instance of {@link Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo }
     * 
     */
    public Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo createObrazacPodaciOPacijentuDrzavljanstvoStranoDrzavljanstvo() {
        return new Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo();
    }

    /**
     * Create an instance of {@link Izvestaj.PeriodIzvestaja.DatumOd }
     * 
     */
    public Izvestaj.PeriodIzvestaja.DatumOd createIzvestajPeriodIzvestajaDatumOd() {
        return new Izvestaj.PeriodIzvestaja.DatumOd();
    }

    /**
     * Create an instance of {@link Izvestaj.PeriodIzvestaja.DatumDo }
     * 
     */
    public Izvestaj.PeriodIzvestaja.DatumDo createIzvestajPeriodIzvestajaDatumDo() {
        return new Izvestaj.PeriodIzvestaja.DatumDo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim.robot/zahtev_za_sertifikat", name = "Razlog_za_odbijanje", scope = Zahtev.class)
    public JAXBElement<String> createZahtevRazlogZaOdbijanje(String value) {
        return new JAXBElement<String>(_ZahtevRazlogZaOdbijanje_QNAME, String.class, Zahtev.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Obrazac.PodaciOPacijentu.SedisteSocijalneZastite }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Obrazac.PodaciOPacijentu.SedisteSocijalneZastite }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim.robot/obrazac_saglasnosti_za_imunizaciju", name = "Sediste_socijalne_zastite", scope = Obrazac.PodaciOPacijentu.class)
    public JAXBElement<Obrazac.PodaciOPacijentu.SedisteSocijalneZastite> createObrazacPodaciOPacijentuSedisteSocijalneZastite(Obrazac.PodaciOPacijentu.SedisteSocijalneZastite value) {
        return new JAXBElement<Obrazac.PodaciOPacijentu.SedisteSocijalneZastite>(_ObrazacPodaciOPacijentuSedisteSocijalneZastite_QNAME, Obrazac.PodaciOPacijentu.SedisteSocijalneZastite.class, Obrazac.PodaciOPacijentu.class, value);
    }

}
