//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 01:09:50 AM CEST 
//


package com.timrobot.vaccapp.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podaci_o_pacijentu"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Drzavljanstvo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="JMBG"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;pattern value="\d{13}"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Strano_drzavljanstvo"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Br_pasosa"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                             &lt;pattern value="\d{9}"/&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Prezime" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TPrezime"/&gt;
 *                   &lt;element name="Ime" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TIme"/&gt;
 *                   &lt;element name="Ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Pol"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Muski"/&gt;
 *                         &lt;enumeration value="Zenski"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Adresa" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TAdresa"/&gt;
 *                   &lt;element name="Naselje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Telefon_fiksni"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="0\d{8,9}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Telefon_mobilni"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="06\d{7,8}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Imejl"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,64}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Radni_status"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Zaposlen"/&gt;
 *                         &lt;enumeration value="Nezaposlen"/&gt;
 *                         &lt;enumeration value="Penzioner"/&gt;
 *                         &lt;enumeration value="Ucenik"/&gt;
 *                         &lt;enumeration value="Student"/&gt;
 *                         &lt;enumeration value="Dete"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Zanimanje_zaposlenog"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Zdravstvena zastita"/&gt;
 *                         &lt;enumeration value="Socijalna zastita"/&gt;
 *                         &lt;enumeration value="Prosveta"/&gt;
 *                         &lt;enumeration value="MUP"/&gt;
 *                         &lt;enumeration value="Vojska RS"/&gt;
 *                         &lt;enumeration value="Drugo"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Korisnik_socijalne_zastite"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="DA"/&gt;
 *                         &lt;enumeration value="NE"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Sediste_socijalne_zastite" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podaci_o_saglasnosti"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Saglasnost"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="SAGLASAN SAM"/&gt;
 *                         &lt;enumeration value="NISAM SAGLASAN"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Naziv_imunoloskog_leka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Datum" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TDatumIzdavanja"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Evidencija_o_vakcinaciji" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Vakcinacijski_punkt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Podaci_o_lekaru"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Broj_telefona"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;pattern value="06\d{7,8}"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Podaci_o_izvrsenim_imunizacijama"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Primljena_vakcina" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TPrimljena_vakcina" maxOccurs="2"/&gt;
 *                             &lt;element name="Privremene_kontraindikacije" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:fromObrazacInteresovanja" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOPacijentu",
    "podaciOSaglasnosti",
    "evidencijaOVakcinaciji"
})
@XmlRootElement(name = "Obrazac")
public class Obrazac {

    @XmlElement(name = "Podaci_o_pacijentu", required = true)
    protected Obrazac.PodaciOPacijentu podaciOPacijentu;
    @XmlElement(name = "Podaci_o_saglasnosti", required = true)
    protected Obrazac.PodaciOSaglasnosti podaciOSaglasnosti;
    @XmlElement(name = "Evidencija_o_vakcinaciji")
    protected Obrazac.EvidencijaOVakcinaciji evidencijaOVakcinaciji;
    @XmlAttribute(name = "about", required = true)
    protected String about;
    @XmlAttribute(name = "href")
    protected String href;
    @XmlAttribute(name = "rel", required = true)
    protected String rel;

    /**
     * Gets the value of the podaciOPacijentu property.
     * 
     * @return
     *     possible object is
     *     {@link Obrazac.PodaciOPacijentu }
     *     
     */
    public Obrazac.PodaciOPacijentu getPodaciOPacijentu() {
        return podaciOPacijentu;
    }

    /**
     * Sets the value of the podaciOPacijentu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obrazac.PodaciOPacijentu }
     *     
     */
    public void setPodaciOPacijentu(Obrazac.PodaciOPacijentu value) {
        this.podaciOPacijentu = value;
    }

    /**
     * Gets the value of the podaciOSaglasnosti property.
     * 
     * @return
     *     possible object is
     *     {@link Obrazac.PodaciOSaglasnosti }
     *     
     */
    public Obrazac.PodaciOSaglasnosti getPodaciOSaglasnosti() {
        return podaciOSaglasnosti;
    }

    /**
     * Sets the value of the podaciOSaglasnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obrazac.PodaciOSaglasnosti }
     *     
     */
    public void setPodaciOSaglasnosti(Obrazac.PodaciOSaglasnosti value) {
        this.podaciOSaglasnosti = value;
    }

    /**
     * Gets the value of the evidencijaOVakcinaciji property.
     * 
     * @return
     *     possible object is
     *     {@link Obrazac.EvidencijaOVakcinaciji }
     *     
     */
    public Obrazac.EvidencijaOVakcinaciji getEvidencijaOVakcinaciji() {
        return evidencijaOVakcinaciji;
    }

    /**
     * Sets the value of the evidencijaOVakcinaciji property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obrazac.EvidencijaOVakcinaciji }
     *     
     */
    public void setEvidencijaOVakcinaciji(Obrazac.EvidencijaOVakcinaciji value) {
        this.evidencijaOVakcinaciji = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel() {
        if (rel == null) {
            return "pred:fromObrazacInteresovanja";
        } else {
            return rel;
        }
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel(String value) {
        this.rel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Vakcinacijski_punkt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Podaci_o_lekaru"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Broj_telefona"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;pattern value="06\d{7,8}"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Podaci_o_izvrsenim_imunizacijama"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Primljena_vakcina" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TPrimljena_vakcina" maxOccurs="2"/&gt;
     *                   &lt;element name="Privremene_kontraindikacije" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                             &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zdravstvenaUstanova",
        "vakcinacijskiPunkt",
        "podaciOLekaru",
        "podaciOIzvrsenimImunizacijama"
    })
    public static class EvidencijaOVakcinaciji {

        @XmlElement(name = "Zdravstvena_ustanova", required = true)
        protected String zdravstvenaUstanova;
        @XmlElement(name = "Vakcinacijski_punkt", required = true)
        protected String vakcinacijskiPunkt;
        @XmlElement(name = "Podaci_o_lekaru", required = true)
        protected Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru podaciOLekaru;
        @XmlElement(name = "Podaci_o_izvrsenim_imunizacijama", required = true)
        protected Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama podaciOIzvrsenimImunizacijama;

        /**
         * Gets the value of the zdravstvenaUstanova property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZdravstvenaUstanova() {
            return zdravstvenaUstanova;
        }

        /**
         * Sets the value of the zdravstvenaUstanova property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZdravstvenaUstanova(String value) {
            this.zdravstvenaUstanova = value;
        }

        /**
         * Gets the value of the vakcinacijskiPunkt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVakcinacijskiPunkt() {
            return vakcinacijskiPunkt;
        }

        /**
         * Sets the value of the vakcinacijskiPunkt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVakcinacijskiPunkt(String value) {
            this.vakcinacijskiPunkt = value;
        }

        /**
         * Gets the value of the podaciOLekaru property.
         * 
         * @return
         *     possible object is
         *     {@link Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru }
         *     
         */
        public Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru getPodaciOLekaru() {
            return podaciOLekaru;
        }

        /**
         * Sets the value of the podaciOLekaru property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru }
         *     
         */
        public void setPodaciOLekaru(Obrazac.EvidencijaOVakcinaciji.PodaciOLekaru value) {
            this.podaciOLekaru = value;
        }

        /**
         * Gets the value of the podaciOIzvrsenimImunizacijama property.
         * 
         * @return
         *     possible object is
         *     {@link Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama }
         *     
         */
        public Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama getPodaciOIzvrsenimImunizacijama() {
            return podaciOIzvrsenimImunizacijama;
        }

        /**
         * Sets the value of the podaciOIzvrsenimImunizacijama property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama }
         *     
         */
        public void setPodaciOIzvrsenimImunizacijama(Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama value) {
            this.podaciOIzvrsenimImunizacijama = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Primljena_vakcina" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TPrimljena_vakcina" maxOccurs="2"/&gt;
         *         &lt;element name="Privremene_kontraindikacije" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                   &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "primljenaVakcina",
            "privremeneKontraindikacije",
            "odlukaKomisije"
        })
        public static class PodaciOIzvrsenimImunizacijama {

            @XmlElement(name = "Primljena_vakcina", required = true)
            protected List<TPrimljenaVakcina> primljenaVakcina;
            @XmlElement(name = "Privremene_kontraindikacije")
            protected Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije privremeneKontraindikacije;
            @XmlElement(name = "Odluka_komisije", required = true)
            protected String odlukaKomisije;

            /**
             * Gets the value of the primljenaVakcina property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the primljenaVakcina property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrimljenaVakcina().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TPrimljenaVakcina }
             * 
             * 
             */
            public List<TPrimljenaVakcina> getPrimljenaVakcina() {
                if (primljenaVakcina == null) {
                    primljenaVakcina = new ArrayList<TPrimljenaVakcina>();
                }
                return this.primljenaVakcina;
            }

            /**
             * Gets the value of the privremeneKontraindikacije property.
             * 
             * @return
             *     possible object is
             *     {@link Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije }
             *     
             */
            public Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije getPrivremeneKontraindikacije() {
                return privremeneKontraindikacije;
            }

            /**
             * Sets the value of the privremeneKontraindikacije property.
             * 
             * @param value
             *     allowed object is
             *     {@link Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije }
             *     
             */
            public void setPrivremeneKontraindikacije(Obrazac.EvidencijaOVakcinaciji.PodaciOIzvrsenimImunizacijama.PrivremeneKontraindikacije value) {
                this.privremeneKontraindikacije = value;
            }

            /**
             * Gets the value of the odlukaKomisije property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOdlukaKomisije() {
                return odlukaKomisije;
            }

            /**
             * Sets the value of the odlukaKomisije property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOdlukaKomisije(String value) {
                this.odlukaKomisije = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datum",
                "dijagnoza"
            })
            public static class PrivremeneKontraindikacije {

                @XmlElement(name = "Datum", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar datum;
                @XmlElement(name = "Dijagnoza", required = true)
                protected String dijagnoza;

                /**
                 * Gets the value of the datum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDatum() {
                    return datum;
                }

                /**
                 * Sets the value of the datum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDatum(XMLGregorianCalendar value) {
                    this.datum = value;
                }

                /**
                 * Gets the value of the dijagnoza property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDijagnoza() {
                    return dijagnoza;
                }

                /**
                 * Sets the value of the dijagnoza property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDijagnoza(String value) {
                    this.dijagnoza = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Broj_telefona"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;pattern value="06\d{7,8}"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "faksimil",
            "brojTelefona"
        })
        public static class PodaciOLekaru {

            @XmlElement(name = "Ime", required = true)
            protected String ime;
            @XmlElement(name = "Prezime", required = true)
            protected String prezime;
            @XmlElement(name = "Faksimil", required = true)
            protected String faksimil;
            @XmlElement(name = "Broj_telefona", required = true)
            protected String brojTelefona;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the faksimil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFaksimil() {
                return faksimil;
            }

            /**
             * Sets the value of the faksimil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFaksimil(String value) {
                this.faksimil = value;
            }

            /**
             * Gets the value of the brojTelefona property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrojTelefona() {
                return brojTelefona;
            }

            /**
             * Sets the value of the brojTelefona property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrojTelefona(String value) {
                this.brojTelefona = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Drzavljanstvo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="JMBG"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;pattern value="\d{13}"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Strano_drzavljanstvo"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Br_pasosa"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                   &lt;pattern value="\d{9}"/&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Prezime" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TPrezime"/&gt;
     *         &lt;element name="Ime" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TIme"/&gt;
     *         &lt;element name="Ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Pol"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Muski"/&gt;
     *               &lt;enumeration value="Zenski"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Adresa" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TAdresa"/&gt;
     *         &lt;element name="Naselje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Grad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Telefon_fiksni"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="0\d{8,9}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Telefon_mobilni"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="06\d{7,8}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Imejl"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,64}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Radni_status"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Zaposlen"/&gt;
     *               &lt;enumeration value="Nezaposlen"/&gt;
     *               &lt;enumeration value="Penzioner"/&gt;
     *               &lt;enumeration value="Ucenik"/&gt;
     *               &lt;enumeration value="Student"/&gt;
     *               &lt;enumeration value="Dete"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Zanimanje_zaposlenog"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Zdravstvena zastita"/&gt;
     *               &lt;enumeration value="Socijalna zastita"/&gt;
     *               &lt;enumeration value="Prosveta"/&gt;
     *               &lt;enumeration value="MUP"/&gt;
     *               &lt;enumeration value="Vojska RS"/&gt;
     *               &lt;enumeration value="Drugo"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Korisnik_socijalne_zastite"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="DA"/&gt;
     *               &lt;enumeration value="NE"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Sediste_socijalne_zastite" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drzavljanstvo",
        "prezime",
        "ime",
        "imeRoditelja",
        "pol",
        "datumRodjenja",
        "mestoRodjenja",
        "adresa",
        "naselje",
        "grad",
        "telefonFiksni",
        "telefonMobilni",
        "imejl",
        "radniStatus",
        "zanimanjeZaposlenog",
        "korisnikSocijalneZastite",
        "sedisteSocijalneZastite"
    })
    public static class PodaciOPacijentu {

        @XmlElement(name = "Drzavljanstvo", required = true)
        protected Obrazac.PodaciOPacijentu.Drzavljanstvo drzavljanstvo;
        @XmlElement(name = "Prezime", required = true)
        protected TPrezime prezime;
        @XmlElement(name = "Ime", required = true)
        protected TIme ime;
        @XmlElement(name = "Ime_roditelja", required = true)
        protected String imeRoditelja;
        @XmlElement(name = "Pol", required = true)
        protected String pol;
        @XmlElement(name = "Datum_rodjenja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumRodjenja;
        @XmlElement(name = "Mesto_rodjenja", required = true)
        protected String mestoRodjenja;
        @XmlElement(name = "Adresa", required = true)
        protected TAdresa adresa;
        @XmlElement(name = "Naselje", required = true)
        protected String naselje;
        @XmlElement(name = "Grad", required = true)
        protected String grad;
        @XmlElement(name = "Telefon_fiksni", required = true)
        protected String telefonFiksni;
        @XmlElement(name = "Telefon_mobilni", required = true)
        protected String telefonMobilni;
        @XmlElement(name = "Imejl", required = true)
        protected String imejl;
        @XmlElement(name = "Radni_status", required = true)
        protected String radniStatus;
        @XmlElement(name = "Zanimanje_zaposlenog", required = true)
        protected String zanimanjeZaposlenog;
        @XmlElement(name = "Korisnik_socijalne_zastite", required = true)
        protected String korisnikSocijalneZastite;
        @XmlElementRef(name = "Sediste_socijalne_zastite", namespace = "http://tim.robot/obrazac_saglasnosti_za_imunizaciju", type = JAXBElement.class, required = false)
        protected JAXBElement<Obrazac.PodaciOPacijentu.SedisteSocijalneZastite> sedisteSocijalneZastite;

        /**
         * Gets the value of the drzavljanstvo property.
         * 
         * @return
         *     possible object is
         *     {@link Obrazac.PodaciOPacijentu.Drzavljanstvo }
         *     
         */
        public Obrazac.PodaciOPacijentu.Drzavljanstvo getDrzavljanstvo() {
            return drzavljanstvo;
        }

        /**
         * Sets the value of the drzavljanstvo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obrazac.PodaciOPacijentu.Drzavljanstvo }
         *     
         */
        public void setDrzavljanstvo(Obrazac.PodaciOPacijentu.Drzavljanstvo value) {
            this.drzavljanstvo = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link TPrezime }
         *     
         */
        public TPrezime getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPrezime }
         *     
         */
        public void setPrezime(TPrezime value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link TIme }
         *     
         */
        public TIme getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIme }
         *     
         */
        public void setIme(TIme value) {
            this.ime = value;
        }

        /**
         * Gets the value of the imeRoditelja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImeRoditelja() {
            return imeRoditelja;
        }

        /**
         * Sets the value of the imeRoditelja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImeRoditelja(String value) {
            this.imeRoditelja = value;
        }

        /**
         * Gets the value of the pol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPol() {
            return pol;
        }

        /**
         * Sets the value of the pol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPol(String value) {
            this.pol = value;
        }

        /**
         * Gets the value of the datumRodjenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumRodjenja() {
            return datumRodjenja;
        }

        /**
         * Sets the value of the datumRodjenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumRodjenja(XMLGregorianCalendar value) {
            this.datumRodjenja = value;
        }

        /**
         * Gets the value of the mestoRodjenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMestoRodjenja() {
            return mestoRodjenja;
        }

        /**
         * Sets the value of the mestoRodjenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMestoRodjenja(String value) {
            this.mestoRodjenja = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link TAdresa }
         *     
         */
        public TAdresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAdresa }
         *     
         */
        public void setAdresa(TAdresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the naselje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaselje() {
            return naselje;
        }

        /**
         * Sets the value of the naselje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaselje(String value) {
            this.naselje = value;
        }

        /**
         * Gets the value of the grad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrad() {
            return grad;
        }

        /**
         * Sets the value of the grad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrad(String value) {
            this.grad = value;
        }

        /**
         * Gets the value of the telefonFiksni property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefonFiksni() {
            return telefonFiksni;
        }

        /**
         * Sets the value of the telefonFiksni property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefonFiksni(String value) {
            this.telefonFiksni = value;
        }

        /**
         * Gets the value of the telefonMobilni property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefonMobilni() {
            return telefonMobilni;
        }

        /**
         * Sets the value of the telefonMobilni property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefonMobilni(String value) {
            this.telefonMobilni = value;
        }

        /**
         * Gets the value of the imejl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImejl() {
            return imejl;
        }

        /**
         * Sets the value of the imejl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImejl(String value) {
            this.imejl = value;
        }

        /**
         * Gets the value of the radniStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRadniStatus() {
            return radniStatus;
        }

        /**
         * Sets the value of the radniStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRadniStatus(String value) {
            this.radniStatus = value;
        }

        /**
         * Gets the value of the zanimanjeZaposlenog property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZanimanjeZaposlenog() {
            return zanimanjeZaposlenog;
        }

        /**
         * Sets the value of the zanimanjeZaposlenog property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZanimanjeZaposlenog(String value) {
            this.zanimanjeZaposlenog = value;
        }

        /**
         * Gets the value of the korisnikSocijalneZastite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKorisnikSocijalneZastite() {
            return korisnikSocijalneZastite;
        }

        /**
         * Sets the value of the korisnikSocijalneZastite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKorisnikSocijalneZastite(String value) {
            this.korisnikSocijalneZastite = value;
        }

        /**
         * Gets the value of the sedisteSocijalneZastite property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link Obrazac.PodaciOPacijentu.SedisteSocijalneZastite }{@code >}
         *     
         */
        public JAXBElement<Obrazac.PodaciOPacijentu.SedisteSocijalneZastite> getSedisteSocijalneZastite() {
            return sedisteSocijalneZastite;
        }

        /**
         * Sets the value of the sedisteSocijalneZastite property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link Obrazac.PodaciOPacijentu.SedisteSocijalneZastite }{@code >}
         *     
         */
        public void setSedisteSocijalneZastite(JAXBElement<Obrazac.PodaciOPacijentu.SedisteSocijalneZastite> value) {
            this.sedisteSocijalneZastite = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="JMBG"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;pattern value="\d{13}"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Strano_drzavljanstvo"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Br_pasosa"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                         &lt;pattern value="\d{9}"/&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "jmbg",
            "stranoDrzavljanstvo"
        })
        public static class Drzavljanstvo {

            @XmlElement(name = "JMBG")
            protected String jmbg;
            @XmlElement(name = "Strano_drzavljanstvo")
            protected Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo stranoDrzavljanstvo;

            /**
             * Gets the value of the jmbg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJMBG() {
                return jmbg;
            }

            /**
             * Sets the value of the jmbg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJMBG(String value) {
                this.jmbg = value;
            }

            /**
             * Gets the value of the stranoDrzavljanstvo property.
             * 
             * @return
             *     possible object is
             *     {@link Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo }
             *     
             */
            public Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo getStranoDrzavljanstvo() {
                return stranoDrzavljanstvo;
            }

            /**
             * Sets the value of the stranoDrzavljanstvo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo }
             *     
             */
            public void setStranoDrzavljanstvo(Obrazac.PodaciOPacijentu.Drzavljanstvo.StranoDrzavljanstvo value) {
                this.stranoDrzavljanstvo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Br_pasosa"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *               &lt;pattern value="\d{9}"/&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "naziv",
                "brPasosa"
            })
            public static class StranoDrzavljanstvo {

                @XmlElement(name = "Naziv", required = true)
                protected String naziv;
                @XmlElement(name = "Br_pasosa", required = true)
                protected String brPasosa;

                /**
                 * Gets the value of the naziv property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNaziv() {
                    return naziv;
                }

                /**
                 * Sets the value of the naziv property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNaziv(String value) {
                    this.naziv = value;
                }

                /**
                 * Gets the value of the brPasosa property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBrPasosa() {
                    return brPasosa;
                }

                /**
                 * Sets the value of the brPasosa property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBrPasosa(String value) {
                    this.brPasosa = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "opstina"
        })
        public static class SedisteSocijalneZastite {

            @XmlElement(name = "Naziv", required = true, nillable = true)
            protected String naziv;
            @XmlElement(name = "Opstina", required = true, nillable = true)
            protected String opstina;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the opstina property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOpstina() {
                return opstina;
            }

            /**
             * Sets the value of the opstina property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOpstina(String value) {
                this.opstina = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Saglasnost"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="SAGLASAN SAM"/&gt;
     *               &lt;enumeration value="NISAM SAGLASAN"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Naziv_imunoloskog_leka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Datum" type="{http://tim.robot/obrazac_saglasnosti_za_imunizaciju}TDatumIzdavanja"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saglasnost",
        "nazivImunoloskogLeka",
        "datum"
    })
    public static class PodaciOSaglasnosti {

        @XmlElement(name = "Saglasnost", required = true)
        protected String saglasnost;
        @XmlElement(name = "Naziv_imunoloskog_leka", required = true)
        protected String nazivImunoloskogLeka;
        @XmlElement(name = "Datum", required = true)
        protected TDatumIzdavanja datum;

        /**
         * Gets the value of the saglasnost property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSaglasnost() {
            return saglasnost;
        }

        /**
         * Sets the value of the saglasnost property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSaglasnost(String value) {
            this.saglasnost = value;
        }

        /**
         * Gets the value of the nazivImunoloskogLeka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivImunoloskogLeka() {
            return nazivImunoloskogLeka;
        }

        /**
         * Sets the value of the nazivImunoloskogLeka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivImunoloskogLeka(String value) {
            this.nazivImunoloskogLeka = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link TDatumIzdavanja }
         *     
         */
        public TDatumIzdavanja getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDatumIzdavanja }
         *     
         */
        public void setDatum(TDatumIzdavanja value) {
            this.datum = value;
        }

    }

}
