//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.13 at 07:08:37 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tim.robot/obrazac_saglasnosti_za_imunizaciju", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.timrobot.vaccapp.models;
