//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.18 at 07:21:59 PM CEST 
//


package com.timrobot.vaccapp.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TKovid_test complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TKovid_test"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Naziv_testa"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="PCR"/&gt;
 *               &lt;enumeration value="Antigen"/&gt;
 *               &lt;enumeration value="IgG"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Proizvodjac_testa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Datum_i_vreme_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Rezultat"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Pozitivan"/&gt;
 *               &lt;enumeration value="Negativan"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TKovid_test", namespace = "http://tim.robot/zeleni_sertifikat", propOrder = {
    "nazivTesta",
    "vrstaUzorka",
    "proizvodjacTesta",
    "datumIVremeUzorkovanja",
    "rezultat",
    "laboratorija"
})
public class TKovidTest {

    @XmlElement(name = "Naziv_testa", required = true)
    protected String nazivTesta;
    @XmlElement(name = "Vrsta_uzorka", required = true)
    protected String vrstaUzorka;
    @XmlElement(name = "Proizvodjac_testa", required = true)
    protected String proizvodjacTesta;
    @XmlElement(name = "Datum_i_vreme_uzorkovanja", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumIVremeUzorkovanja;
    @XmlElement(name = "Rezultat", required = true)
    protected String rezultat;
    @XmlElement(name = "Laboratorija", required = true)
    protected String laboratorija;

    /**
     * Gets the value of the nazivTesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivTesta() {
        return nazivTesta;
    }

    /**
     * Sets the value of the nazivTesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivTesta(String value) {
        this.nazivTesta = value;
    }

    /**
     * Gets the value of the vrstaUzorka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaUzorka() {
        return vrstaUzorka;
    }

    /**
     * Sets the value of the vrstaUzorka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaUzorka(String value) {
        this.vrstaUzorka = value;
    }

    /**
     * Gets the value of the proizvodjacTesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProizvodjacTesta() {
        return proizvodjacTesta;
    }

    /**
     * Sets the value of the proizvodjacTesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProizvodjacTesta(String value) {
        this.proizvodjacTesta = value;
    }

    /**
     * Gets the value of the datumIVremeUzorkovanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIVremeUzorkovanja() {
        return datumIVremeUzorkovanja;
    }

    /**
     * Sets the value of the datumIVremeUzorkovanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIVremeUzorkovanja(XMLGregorianCalendar value) {
        this.datumIVremeUzorkovanja = value;
    }

    /**
     * Gets the value of the rezultat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRezultat() {
        return rezultat;
    }

    /**
     * Sets the value of the rezultat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRezultat(String value) {
        this.rezultat = value;
    }

    /**
     * Gets the value of the laboratorija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaboratorija() {
        return laboratorija;
    }

    /**
     * Sets the value of the laboratorija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaboratorija(String value) {
        this.laboratorija = value;
    }

}
